version: 2.1
orbs:
  architect: giantswarm/architect@4.15.0

workflows:
  build:
    jobs:
      - architect/go-test:
          name: go-test
          # Needed to trigger job also on git tag.
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/

      - architect/go-build:
          name: go-build
          requires:
            - go-test
          binary: gscliauth
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
